### ISSUE TITLE
Bower Install tafgeetjs

### ISSUE THREAD

**Issue by kishoreaoe** [mmahgoub/tafgeetjs#5]
Could not able to download tafgeetjs with  bower install. Any help Please.!

**Comment by mmahgoub** [comment]
tafgeetjs isn't published on bower but let me see what I can do

**Comment by mmahgoub** [comment]
@kishoreaoe Registered tafgeetjs on Bower you can now install it using the install command, but I need to mention that Bower themselves not recommending using bower they encourage people to move to Webpack or Yarn
